export const cityNames = { Seattle: '西雅图', Taipei: '台北', Kaohsiung: '高雄', Shanghai: '上海', Suzhou: '苏州', Lanzhou: '兰州', Dunhuang: '敦煌', Chengdu: '成都', Chongqing: '重庆', Yichang: '宜昌', Huangshi: '黄石', Wuhan: '武汉', Seoul: '首尔', Guanghan: '广汉', Guazhou: '瓜州', Dazu: '大足', 'Yangtze River': '长江', 'Chengdu Tianfu': '成都天府机场', 'Shanghai Pudong': '上海浦东机场', 'Shanghai Hongqiao': '上海虹桥机场', 'Seoul Incheon': '首尔仁川机场', 'Trip essentials': '行前事项' };
export const timelineLabels = { '概览': '当日概览', 'Check in': '入住', 'Check out': '退房', Transport: '交通', 'Flight departure': '航班起飞', 'Flight arrival': '航班抵达', 'Staying tonight': '今晚住宿', 'Optional / backup': '备选安排', 'Board cruise': '登船', 'Disembark': '下船', 'Aboard the cruise': '游轮上', 'In flight': '飞行途中', 'Plan': '计划活动', 'Reservation': '预订事项', 'Room reserved for arrival after midnight': '已为午夜后抵达保留客房' };
export const zhTime = (value) => {
    const overnight = value.match(/^(\d{1,2}:\d{2}) departure → (\d{1,2}:\d{2}) arrival on (Oct|Nov) (\d{1,2})$/);
    if (overnight)
        return `${overnight[1]} 起飞 → ${overnight[3] === 'Oct' ? '10' : '11'}月${overnight[4]}日 ${overnight[2]} 抵达`;
    const exact = { 'After flight arrival · pickup time to arrange': '抵达后接车，时间待安排', 'Before the flight · departure time to arrange': '起飞前出发，时间待安排', 'Before boarding · time to arrange': '登船前，时间待安排', 'After disembarkation · time to arrange': '下船后，时间待安排', 'Time to arrange': '时间待安排', 'Checkout time to confirm': '退房时间待确认', 'After the airport transfer': '机场接驳后', 'After arrival and transfer': '抵达并完成接驳后', 'After the journey': '抵达后', 'Check-in time to confirm': '入住时间待确认', 'Boarding time to confirm': '登船时间待确认', 'Disembarkation time to confirm': '下船时间待确认', 'After the journey · time to arrange': '抵达后，时间待安排', 'Early morning in the plan · exact time to arrange': '清晨，具体时间待安排', 'Morning in the plan · exact time to arrange': '上午，具体时间待安排', 'Late afternoon in the plan · exact time to arrange': '傍晚，具体时间待安排', 'Afternoon in the plan · exact time to arrange': '下午，具体时间待安排', 'Evening in the plan · exact time to arrange': '晚上，具体时间待安排' };
    if (exact[value])
        return exact[value];
    return value.replace(/\b(Oct|Nov)\s+(\d{1,2})\b/g, (_, month, day) => `${month === 'Oct' ? '10' : '11'}月${day}日`).replace(/\bdeparture\b/g, '起飞').replace(/\barrival\b/g, '抵达').replace(/\bon\s+(\d+月\d+日)/g, '，$1').replace(/\(local time\)/g, '（当地时间）').replace(/\blocal times\b/g, '当地时间').replace(/\btarget arrival at airport\b/g, '预计抵达机场').replace(/\bTime to add\b/g, '时间待补充').replace(/\bFull day\b/gi, '全天').replace(/\bMorning\b/gi, '上午').replace(/\bAfternoon\b/gi, '下午').replace(/\bEvening\b/gi, '晚上');
};
