import {getTripProgress} from './progress.mjs';
let libraries;
async function ready(){if(!libraries)libraries=Promise.all([new Promise((resolve,reject)=>{if(window.L)return resolve();const script=document.createElement('script');script.src='./leaflet.js';script.onload=resolve;script.onerror=reject;document.head.append(script);const css=document.createElement('link');css.rel='stylesheet';css.href='./leaflet.css';document.head.append(css)}),fetch('./land.json').then(r=>r.json())]);return libraries}
export async function mountMap(root,ctx){const {data,city,date,esc,card,photo,focusCity,safeUrl}=ctx;const [,land]=await ready();if(!root.isConnected)return()=>{};const L=window.L;
const p=getTripProgress(new Date(),data.map.stops);let chosen=p.dateLabel<data.trip.start?data.trip.start:p.dateLabel>data.trip.end?data.trip.end:p.dateLabel;
root.innerHTML=`<p class="muted">拖动或缩放地图，点击城市和地点了解更多。地图依据计划日期显示大致位置，不代表已实际抵达。</p><div class="map-controls"><label>查看日期 <input type="date" id="map-date" min="${esc(data.trip.start)}" max="${esc(data.trip.end)}" value="${esc(chosen)}"></label><button type="button" id="map-all">完整路线</button><button type="button" id="map-asia">亚洲路线</button></div><div class="map" id="journey-map" aria-label="互动行程地图"></div><p class="map-key">实线：所选日期前的计划路线　虚线：后续计划路线 · 地图为概览，不用于导航。</p><div id="map-places"></div><section class="map-info" id="map-info" aria-live="polite"></section>`;
const map=L.map(root.querySelector('#journey-map'),{minZoom:2,maxZoom:17,attributionControl:true,zoomControl:false,worldCopyJump:false});L.control.zoom({zoomInTitle:'放大',zoomOutTitle:'缩小'}).addTo(map);map.attributionControl.setPrefix(false);map.attributionControl.addAttribution('地图轮廓：Natural Earth · 公共领域');
const shift=geometry=>{if(geometry.type==='GeometryCollection')return {...geometry,geometries:geometry.geometries.map(shift)};const coords=v=>typeof v[0]==='number'?[v[0]+360,v[1]]:v.map(coords);return {...geometry,coordinates:coords(geometry.coordinates)}};
const base={style:{color:'#c4d2c2',weight:1,fillColor:'#f9f8ed',fillOpacity:1},interactive:false};L.geoJSON(land,base).addTo(map);L.geoJSON({...land,features:land.features.map(f=>({...f,geometry:shift(f.geometry)}))},base).addTo(map);
const lng=n=>n<0?n+360:n,point=x=>[x.lat,lng(x.lng)],route=data.map.stops;const paths=L.layerGroup().addTo(map),markers=L.layerGroup().addTo(map),locals=L.layerGroup().addTo(map);let activeCity='';
function title(x){return data.placeNames[x.title]||x.guide?.chineseName||x.title||city(x.city)}
function info(x){const box=root.querySelector('#map-info'),g=x.guide,description=g?.description||x.description||'',zh=data.guideTranslations[description]||description;const name=x.title?title(x):city(x.city);const related=data.entries.filter(e=>x.entryIds?.includes(e.id));box.innerHTML=`<article class="guide"><div class="guide-top"><h2>${esc(name)}</h2><button type="button" id="close-guide" aria-label="收起地点介绍">收起</button></div>${x.arrival?`<p class="meta">${esc(date(x.arrival))}—${esc(date(x.departure))}</p>`:''}${zh?`<p>${esc(zh)}</p>`:''}${g?.photo?'<div class="guide-image"><p class="muted">正在载入照片……</p></div>':''}${g&&safeUrl(g.infoUrlZh||g.infoUrl)?`<a href="${esc(safeUrl(g.infoUrlZh||g.infoUrl))}" target="_blank" rel="noopener noreferrer">进一步了解 ↗</a>`:''}${!x.arrival&&related.length?`<h3>相关安排</h3>${related.map(e=>card(e)).join('')}`:''}</article>`;box.querySelector('#close-guide').onclick=()=>{box.innerHTML=''};if(g?.photo){const holder=box.querySelector('.guide-image');photo(g.photo.url).then(src=>{if(!holder.isConnected)return;if(!src){holder.innerHTML='<p class="muted">照片暂时无法载入。</p>';return}holder.innerHTML=`<img src="${src}" alt="${esc(name)}" loading="lazy" decoding="async"><p class="photo-credit">图片：${esc(g.photo.credit||'原网站')}${g.photo.license?' · '+esc(g.photo.license):''}${safeUrl(g.photo.sourceUrl)?` · <a href="${esc(safeUrl(g.photo.sourceUrl))}" target="_blank" rel="noopener noreferrer">图片来源</a>`:''}</p>`})}}
function select(c,stop){activeCity=c;locals.clearLayers();const places=data.map.places.filter(x=>x.city===c);for(const x of places){const color=x.kind==='hotel'?'#7d637e':x.kind==='airport'?'#768796':x.kind==='restaurant'?'#b88845':'#276b57';const marker=L.circleMarker(point(x),{radius:7,color:'#fff',weight:2,fillColor:color,fillOpacity:1}).addTo(locals);marker.bindTooltip(title(x),{direction:'top'});marker.on('click',()=>info(x));}const ordered=places.filter(x=>Number.isFinite(x.routeOrder)).sort((a,b)=>a.routeOrder-b.routeOrder);if(ordered.length>1)L.polyline(ordered.map(point),{color:'#b8924e',weight:3,dashArray:'3 8'}).addTo(locals);root.querySelector('#map-places').innerHTML=`<h3>${esc(city(c))} · 地点</h3>`+places.map((x,i)=>`<button class="place-button" type="button" data-place="${i}">${esc(title(x))}</button>`).join('');root.querySelectorAll('[data-place]').forEach(b=>b.onclick=()=>{const x=places[+b.dataset.place];map.setView(point(x),13);info(x)});const bounds=places.length?places.map(point):stop?[point(stop)]:[];if(bounds.length)map.fitBounds(bounds,{padding:[35,35],maxZoom:12});if(stop)info(stop)}
function draw(){paths.clearLayers();markers.clearLayers();route.forEach((s,i)=>{if(i){const previous=route[i-1];if(s.id!=='yangtze'&&previous.id!=='yangtze')L.polyline([point(previous),point(s)],{color:s.arrival>chosen?'#8aa599':'#2e6b56',weight:3,dashArray:s.arrival>chosen?'3 9':null}).addTo(paths)}const label=L.marker(point(s),{icon:L.divIcon({className:'map-city-label',html:esc(city(s.city)),iconSize:null,iconAnchor:[20,12]})}).addTo(markers);label.on('click',()=>select(s.city,s));if(s.riverRoute){L.polyline(s.riverRoute.points,{color:'#397bb4',weight:4,dashArray:chosen<s.departure?'3 9':null}).addTo(paths);if(s.riverRoute.shorePoints?.length)L.polyline(s.riverRoute.shorePoints,{color:'#ae8850',weight:3,dashArray:'3 9'}).addTo(paths)}});const current=[...route].reverse().find(s=>s.arrival<=chosen);if(current){L.marker(point(current),{interactive:false,zIndexOffset:1000,icon:L.divIcon({className:'map-current',html:current.id==='yangtze'?'🚢':'📍',iconSize:[30,36],iconAnchor:[15,38]})}).addTo(markers)}}
root.querySelector('#map-date').onchange=e=>{chosen=e.target.value||chosen;draw()};root.querySelector('#map-all').onclick=()=>map.fitBounds(route.map(point),{padding:[35,35]});root.querySelector('#map-asia').onclick=()=>map.fitBounds(route.filter(s=>s.city!=='Seattle').map(point),{padding:[35,35]});draw();map.fitBounds(route.filter(s=>s.city!=='Seattle').map(point),{padding:[35,35]});if(focusCity)select(focusCity,route.find(s=>s.city===focusCity));else{const current=route[p.currentStopIndex]||route.find(s=>s.city!=='Seattle');if(current)info(current)}return()=>map.remove();
}
