import {unlock,validKey} from './crypto.mjs';
import {buildDayTimeline} from './timeline.mjs';
import {getTripProgress} from './progress.mjs';
import {cityNames,timelineLabels,zhTime} from './format.mjs';
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const tabs=[['timeline','每日行程'],['cities','按城市'],['map','地图'],['flight','航班'],['hotel','酒店'],['transport','交通'],['reservation','预订和门票'],['task','待安排']];
const types={flight:'航班',hotel:'酒店',transport:'交通',reservation:'预订和门票',activity:'活动',task:'待安排'};
const statuses={booked:'已预订',confirmed:'已确认',tentative:'暂定',todo:'待安排',done:'已完成'};
const date=s=>new Date(s+'T12:00:00Z').toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long',timeZone:'UTC'});
const time=s=>new Date(s).toLocaleString('zh-CN',{month:'long',day:'numeric',hour:'2-digit',minute:'2-digit'});
const city=s=>s.split(/\s*[·/→↔]\s*/).map(v=>cityNames[v.trim()]||v.trim()).join(' · ');
const safeUrl=s=>{try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:''}catch{return ''}};
let key=new URLSearchParams(location.hash.slice(1)).get('k')||'';
try{if(!key)key=localStorage.getItem('family-private-key')||''}catch{}
let data=null,meta=null,version='',tab='timeline',query='',selectedCity='',reading=false,lastAttempt=0,disposeMap=null,photoPromises=new Map();
const expanded=new Map();
const cacheName='family-encrypted-data-v1';
async function cached(name){try{const cache=await caches.open(cacheName);return await (await cache.match(new URL(name,location.href)))?.json()}catch{return null}}
async function remember(name,value){try{const cache=await caches.open(cacheName);await cache.put(new URL(name,location.href),new Response(JSON.stringify(value),{headers:{'Content-Type':'application/json'}}))}catch{}}
async function json(url){const response=await fetch(url,{cache:'no-store',credentials:'omit',signal:AbortSignal.timeout(20000)});if(!response.ok)throw Error('Connection unavailable');return response.json()}
function tr(e,field){const translated=data.translations?.[e.id]?.[field];return translated?.source===e[field]&&translated.zh?translated.zh:e[field]||''}
function stale(e){return ['title','details','location'].some(field=>e[field]&&/[A-Za-z]{3}/.test(e[field])&&data.translations?.[e.id]?.[field]?.source!==e[field])}
function currentDay(){const p=getTripProgress(new Date(),data.map.stops);return p.dateLabel<data.trip.start?data.trip.start:p.dateLabel>data.trip.end?data.trip.end:p.dateLabel}
function filtered(){return data.entries.filter(e=>(!selectedCity||e.city.split(/→|↔|\/|·/).some(c=>c.trim()===selectedCity))&&[e.title,e.details,e.city,e.location,e.reference,tr(e,'title'),tr(e,'details'),tr(e,'location')].join(' ').toLowerCase().includes(query.toLowerCase()))}
function card(e,item){const title=tr(e,'title'),details=tr(e,'details');const clock=item?.timeLabel?zhTime(item.timeLabel):[e.time,e.endTime].filter(Boolean).map(zhTime).join('—');return `<article class="card"><div class="card-top"><span>${types[e.type]||'安排'}</span><span class="tag ${esc(e.status)}">${statuses[e.status]||'待确认'}</span></div><h3>${item?.arrivalOnly?'抵达 · ':''}${esc(title)}</h3><p class="meta">${esc(city(e.city))} · ${esc(date(e.start))}${e.end!==e.start?'—'+esc(date(e.end)):''}${clock?' · '+esc(clock):''}</p>${e.location?`<p><b>地点：</b>${esc(tr(e,'location'))}</p>`:''}${!item?.arrivalOnly&&details?`<p>${esc(details)}</p>`:''}${e.reference||e.type==='flight'?`<div class="booking">${e.reference?`<p><b>预订编号：</b>${esc(e.reference)}</p>`:''}${e.type==='flight'?`<p><b>关忆：</b>票号 ${esc(e.guanyiTicket||'待补充')} · 座位 ${esc(e.guanyiSeat||'待补充')}</p><p><b>安德鲁：</b>票号 ${esc(e.andrewTicket||'待补充')} · 座位 ${esc(e.andrewSeat||'待补充')}</p>${e.seatNotes?`<p>${esc(e.seatNotes)}</p>`:''}`:''}</div>`:''}${title!==e.title||details!==e.details?`<details class="original"><summary>查看英文原文</summary><p>${esc(e.title)}</p>${!item?.arrivalOnly?`<p>${esc(e.details)}</p>`:''}</details>`:''}${safeUrl(e.url)?`<p><a href="${esc(safeUrl(e.url))}" target="_blank" rel="noopener noreferrer">查看相关网站 ↗</a></p>`:''}${stale(e)?'<p class="translation">此项有新的英文内容，中文翻译待更新。</p>':''}</article>`}
function updateStatus(offline=false){if(!data)return;const p=getTripProgress(new Date(),data.map.stops),stop=data.map.stops[p.currentStopIndex];$('where').textContent=p.phase==='before'?'旅程尚未开始，期待出发':p.phase==='after'?'旅程已结束，平安归来':`今天的计划位置：${city(stop?.city||'')}`;const age=meta?.checkedAt?Date.now()-Date.parse(meta.checkedAt):Infinity;$('sync').textContent=(offline?'暂时离线 · 显示已保存的行程':'已读取 GitHub 上的行程')+(meta?.checkedAt?' · 最近同步：'+time(meta.checkedAt):'')+(Number.isFinite(age)&&age>3600000?' · 同步可能延迟':'');const count=data.entries.filter(stale).length;const notices=[];if(age>3600000)notices.push('当前显示上次成功同步的内容，新的修改可能尚未传过来。');if(count)notices.push(`有 ${count} 条行程包含尚未翻译的英文更新，可请关忆更新中文。`);$('warning').hidden=!notices.length;$('warning').textContent=notices.join(' ')}
function render(){if(!data)return;disposeMap?.();disposeMap=null;$('tabs').innerHTML=tabs.map(([id,title])=>`<button type="button" data-tab="${id}" class="${tab===id?'active':''}" aria-pressed="${tab===id}">${title}</button>`).join('');const entries=filtered(),allowed=new Set(entries.map(e=>e.id));$('search').parentElement.hidden=tab==='map';const content=$('content');if(tab==='timeline'){
 const dates=[];for(let d=data.trip.start;d<=data.trip.end;d=new Date(Date.parse(d+'T12:00Z')+86400000).toISOString().slice(0,10))dates.push(d);
 content.innerHTML=dates.map(d=>{const plan=buildDayTimeline(data.entries,d);const items=[...plan.overview.map(entry=>({entry,label:'概览'})),...plan.schedule,...plan.flexible,...plan.stays,...plan.alternatives].filter(item=>allowed.has(item.entry.id));if((query||selectedCity)&&!items.length)return '';const focus=d===currentDay();const open=expanded.get(d)??(focus||!!query||!!selectedCity);return `<details class="day ${focus?'focus':''}" id="day-${d}" data-day="${d}" ${open?'open':''}><summary><span>${esc(date(d))} · ${esc(city(items.find(i=>i.entry.id==='day-'+d)?.entry.city||items[0]?.entry.city||''))}</span></summary><div class="day-body">${items.map(item=>`<div class="section-label">${esc(timelineLabels[item.label]||'安排')}</div>`+card(item.entry,item)).join('')||'<p class="empty">当天暂无安排</p>'}</div></details>`}).join('');
 content.querySelectorAll('.day').forEach(el=>el.addEventListener('toggle',()=>expanded.set(el.dataset.day,el.open)));
 }else if(tab==='cities'){const cities=[...new Set(entries.flatMap(e=>e.city.split(/→|↔|\/|·/).map(x=>x.trim())))];content.innerHTML=cities.map(c=>`<section><div class="city-head"><h2>${esc(city(c))}</h2><button type="button" data-map-city="${esc(c)}">在地图上查看</button></div>${entries.filter(e=>e.city.split(/→|↔|\/|·/).map(x=>x.trim()).includes(c)).sort((a,b)=>a.start.localeCompare(b.start)||a.time.localeCompare(b.time)).map(e=>card(e)).join('')}</section>`).join('')||'<p class="empty">没有符合条件的安排</p>';
 }else if(tab==='map'){content.innerHTML='<p class="muted">正在载入轻量地图……</p>';import('./map.mjs').then(async module=>{if(tab!=='map')return;disposeMap=await module.mountMap(content,{data,city,date,esc,card,photo:loadPhoto,focusCity:selectedCity,safeUrl})}).catch(()=>{content.innerHTML='<p class="notice">地图暂时无法载入，请点“更新行程”重试。</p>'})
 }else{content.innerHTML=entries.filter(e=>e.type===tab).sort((a,b)=>a.start.localeCompare(b.start)||a.time.localeCompare(b.time)).map(e=>card(e)).join('')||'<p class="empty">没有符合条件的安排</p>'}}
function accept(snapshot,manifest,envelope){if(snapshot.schema!==1||!Array.isArray(snapshot.entries)||!snapshot.map?.stops)throw Error('Invalid trip data');const first=!data;data=snapshot;meta=manifest;version=envelope.version;$('gate').hidden=true;$('app').hidden=false;$('trip-title').textContent=data.trip.title;$('trip-dates').textContent=`${date(data.trip.start)}—${date(data.trip.end)}`;const cities=[...new Set(data.entries.flatMap(e=>e.city.split(/→|↔|\/|·/).map(v=>v.trim())))];$('city').innerHTML='<option value="">所有城市</option>'+cities.map(c=>`<option value="${esc(c)}">${esc(city(c))}</option>`).join('');$('city').value=selectedCity;render();updateStatus();try{localStorage.setItem('family-private-key',key)}catch{}if(first&&new Date().toISOString().slice(0,10)>=data.trip.start)requestAnimationFrame(()=>goToday());}
async function refresh(force=false){if(reading||(!force&&Date.now()-lastAttempt<30000)||!validKey(key))return;reading=true;lastAttempt=Date.now();$('refresh').disabled=true;try{const manifest=await json('./version.json?t='+Date.now());if(!data||manifest.version!==version){const envelope=await json('./snapshot.json?v='+encodeURIComponent(manifest.version));const snapshot=await unlock(envelope,key);accept(snapshot,manifest,envelope);await remember('cached-snapshot',{manifest,envelope})}else{meta=manifest;updateStatus();await remember('cached-manifest',manifest)}}catch{if(data)updateStatus(true);else $('gate-message').textContent='暂时无法打开行程。请确认使用的是完整私人链接，并稍后重试；如从微信打不开，可选择“在浏览器打开”。'}finally{reading=false;$('refresh').disabled=false}}
async function loadPhoto(url){if(!url)return null;const group=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(url)))[0]%16;const expected=meta?.photosVersions?.[group];const cacheKey=group+':'+expected;if(!photoPromises.has(cacheKey))photoPromises.set(cacheKey,(async()=>{const saved=await cached('cached-photos-'+group);if(saved&&saved.version===expected){try{return await unlock(saved,key)}catch{}}const envelope=await json('./photos-'+group+'.json?v='+encodeURIComponent(expected||''));const photos=await unlock(envelope,key);await remember('cached-photos-'+group,envelope);return photos})().catch(()=>{photoPromises.delete(cacheKey);return {}}));return (await photoPromises.get(cacheKey))[url]||null}
function goToday(){if(!data)return;tab='timeline';query='';selectedCity='';$('search').value='';$('city').value='';expanded.set(currentDay(),true);render();$('day-'+currentDay())?.scrollIntoView({block:'start',behavior:'instant'})}
$('tabs').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b){tab=b.dataset.tab;render()}});$('content').addEventListener('click',e=>{const b=e.target.closest('[data-map-city]');if(b){selectedCity=b.dataset.mapCity;tab='map';render()}});$('search').addEventListener('input',e=>{query=e.target.value;render()});$('city').addEventListener('change',e=>{selectedCity=e.target.value;render()});$('refresh').addEventListener('click',()=>refresh(true));$('today').addEventListener('click',goToday);
window.addEventListener('hashchange',()=>location.reload());
window.addEventListener('online',()=>refresh());window.addEventListener('offline',()=>updateStatus(true));window.addEventListener('pageshow',()=>refresh());document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible'){updateStatus(!navigator.onLine);refresh()}});
if(validKey(key)){if(!crypto.subtle||!globalThis.DecompressionStream){$('gate-message').textContent='当前浏览器版本较旧，请用更新版本的 Safari、Chrome 或手机系统浏览器打开。'}else{const saved=await cached('cached-snapshot');if(saved){try{const snapshot=await unlock(saved.envelope,key);const latest=await cached('cached-manifest');accept(snapshot,latest?.version===saved.envelope.version?latest:saved.manifest,saved.envelope);updateStatus(!navigator.onLine)}catch{}}await refresh(true)}}
if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
